### ISSUE TITLE
Missing opencbm.h include

### ISSUE THREAD

**Issue by Pokefinder-org** [ProbablyNotArtyom/DiskImagery64#3]
make complains with

In file included from opencbmwin.cpp:1:
opencbmwin.h:6:10: fatal error: opencbm.h: No such file or directory
 #include <opencbm.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:715: opencbmwin.o] Error 1

**Comment by ProbablyNotArtyom** [comment]
whoops! this is happening because i accidentally pushed unfinished OpenCBM/ZoomFloppy support to master. I'll fix this now.

**Comment by ProbablyNotArtyom** [comment]
This issue has been fixed by the latest commit to master.
